import Head from 'next/head'
import styles from '../styles/Home.module.css'
import IDVCComponent from '../components/IDVC';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next & IDVC2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1>Next.js & IDVC2 App</h1>
        <div id="videoCapturingEl" className={styles.videoCapturingEl}>

        </div>
        <IDVCComponent/>
      </main>
    </>
  )
}
